### ISSUE TITLE
Can you provide us a small sample of the LANL dataset you used in the work?

### ISSUE THREAD

**Issue by luisfredgs** [zazyzaya/EulerTemporalLP#5]
Hello. Firstly, thanks for sharing the source code. There is any version of your paper on Arxiv?  Besides, I would stay quite grateful if you provide a small sample of the LANL dataset you used in the work. 

Secondly, could you explain the "nmap.pkl" on this line from `load_lanl.py`?
 
`nm = pickle.load(open(LANL_FOLDER+'nmap.pkl', 'rb'))`

https://github.com/zazyzaya/EulerTemporalLP/blob/33034e38b422beb1c134344925350380371231f9/loaders/load_lanl.py#L111

**Comment by zazyzaya** [comment]
Hello. I don't have a version on arXiv, but it's freely accessible on the NDSS website:
https://www.ndss-symposium.org/wp-content/uploads/2022-107A-paper.pdf
I'll also put it in the repo

The LANL data set is also open source. This code only uses the auth.txt.gz file available here:
https://csr.lanl.gov/data/cyber1/

Lastly, the `nm` or `node_map` variable is an array that maps node id's to the entity name. So `nm[0]` may point to something like `USER0123`, meaning that's what the node with ID 0 is referring to. I don't believe it is used in any of the LANL tests--it's probably a remnant of some older dataset I was working on. It's loaded from memory because LANL is huge, and it's pretty time consuming to build it every time.

**Comment by luisfredgs** [comment]
Thank you.
